import type { Metadata } from "next";
import Link from "next/link";
import { Crown, Medal, Sparkles, TrendingUp, ShieldCheck } from "lucide-react";

export const metadata: Metadata = { title: "TecPey Academy Hall of Fame", description: "Top learners and achievements in TecPey Academy." };
const students = [
  { name: "Risk Excellence Learner", label: "Best Risk Manager", score: 96, icon: ShieldCheck },
  { name: "Most Improved Learner", label: "Most Improved", score: 94, icon: TrendingUp },
  { name: "Precision Analyst", label: "Top Analyst", score: 93, icon: Medal },
];
export default function Page() { return <main className="min-h-screen bg-[color:var(--tp-bg)] px-4 py-10 text-[color:var(--tp-text)] sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl space-y-8"><section className="rounded-[40px] border border-amber-300/25 bg-[radial-gradient(circle_at_top,rgba(251,191,36,.22),transparent_36%),linear-gradient(145deg,#07111f,#111827)] p-8 text-center text-white"><Crown className="mx-auto h-16 w-16 text-amber-300" /><h1 className="mt-5 text-4xl font-black sm:text-6xl">TecPey Academy Hall of Fame</h1><p className="mx-auto mt-4 max-w-3xl text-sm font-bold leading-8 text-slate-300">A place to recognize learning discipline, risk awareness and responsible improvement — not profit claims or trading signals.</p></section><section className="grid gap-5 md:grid-cols-3">{students.map((student,index)=>{const Icon=student.icon;return <article key={student.label} className="rounded-[34px] border border-amber-300/20 bg-white/95 p-6 text-center shadow-sm dark:bg-white/[0.06]"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-amber-400/15"><Icon className="h-8 w-8 text-amber-500" /></div><p className="mt-4 text-xs font-black text-amber-600">#{index+1} · {student.label}</p><h2 className="mt-2 text-2xl font-black">{student.name}</h2><p className="mt-3 text-4xl font-black text-cyan-500">{student.score}</p></article>})}</section><section className="rounded-[34px] border border-cyan-300/20 bg-cyan-500/10 p-6"><div className="flex gap-3"><Sparkles className="h-6 w-6 text-cyan-500" /><p className="text-sm font-black leading-8">Real positions are calculated from learning records, assessments, simulator practice and mentor feedback after account completion.</p></div></section><Link href="/en/academy/profile" className="inline-flex rounded-2xl bg-cyan-500 px-6 py-3 text-sm font-black text-white">Open my record</Link></div></main>; }
