export const ACADEMY_XP = {
  LESSON_COMPLETE: 30,
  LESSON_PERFECT_BONUS: 50,
  LESSON_PERFECT_TOTAL: 80,
  MODULE_QUIZ_PASS: 50,
  MODULE_QUIZ_PERFECT: 80,
  FLASHCARD_SESSION: 10,
  AI_MENTOR_SESSION: 15,
  STREAK_MAINTAIN: 15,
  STREAK_BONUS_30: 200,
  STREAK_BONUS_100: 500,
  TERM_PASS: 500,
} as const;

export const XP_TABLE = {
  LESSON_COMPLETE: ACADEMY_XP.LESSON_COMPLETE,
  LESSON_PERFECT: ACADEMY_XP.LESSON_PERFECT_TOTAL,
  MODULE_QUIZ_PASS: ACADEMY_XP.MODULE_QUIZ_PASS,
  MODULE_QUIZ_PERFECT: ACADEMY_XP.MODULE_QUIZ_PERFECT,
  FLASHCARD_SESSION: ACADEMY_XP.FLASHCARD_SESSION,
  AI_MENTOR_SESSION: ACADEMY_XP.AI_MENTOR_SESSION,
  STREAK_MAINTAIN: ACADEMY_XP.STREAK_MAINTAIN,
  STREAK_BONUS_30: ACADEMY_XP.STREAK_BONUS_30,
  STREAK_BONUS_100: ACADEMY_XP.STREAK_BONUS_100,
} as const;
