import { SignJWT, jwtVerify } from "jose";
import type { NextRequest, NextResponse } from "next/server";
import { UNIFIED_SESSION_COOKIE, verifyUnifiedSession } from "./unified-session";

export const ACADEMY_AUTH_COOKIE = "tecpey_academy_auth";

export type AcademyAuthSession = {
  accountId: string;
  email: string;
  displayName?: string;
  username?: string;
};

function authSecret() {
  const secret = process.env.TECPEY_ACADEMY_AUTH_SECRET || process.env.TECPEY_SESSION_SECRET || process.env.JWT_SECRET || process.env.NEXTAUTH_SECRET;
  if (secret && secret.length >= 24) return new TextEncoder().encode(secret);
  if (process.env.NODE_ENV !== "production") {
    return new TextEncoder().encode("tecpey-local-academy-auth-dev-secret-please-set-env");
  }
  return null;
}

export function isAcademyAuthConfigured() {
  return Boolean(authSecret());
}

export function normalizeAcademyEmail(value: unknown) {
  return String(value || "").trim().toLowerCase().slice(0, 180);
}

export function normalizeAcademyUsername(value: unknown) {
  return String(value || "").trim().toLowerCase().replace(/[^a-z0-9_.-]/g, "").slice(0, 32);
}

export function academyAccountIdFromEmail(email: string) {
  const safe = normalizeAcademyEmail(email);
  // Deterministic enough for local academy identity and safe to use as an internal subject.
  // The real public student id is still generated by the academy profile service.
  return `academy:${safe}`;
}

export async function signAcademyAuthSession(session: AcademyAuthSession) {
  const key = authSecret();
  if (!key) throw new Error("academy_auth_secret_missing");
  return new SignJWT({
    role: "academy_user",
    email: session.email,
    displayName: session.displayName || "",
    username: session.username || "",
  })
    .setProtectedHeader({ alg: "HS256" })
    .setSubject(session.accountId)
    .setIssuedAt()
    .setExpirationTime(process.env.TECPEY_ACADEMY_AUTH_MAX_AGE || "30d")
    .sign(key);
}

export async function verifyAcademyAuthToken(token?: string | null): Promise<AcademyAuthSession | null> {
  if (!token) return null;
  const key = authSecret();
  if (!key) return null;
  try {
    const { payload } = await jwtVerify(token, key, { algorithms: ["HS256"] });
    if (payload.role !== "academy_user" || typeof payload.sub !== "string" || typeof payload.email !== "string") return null;
    return {
      accountId: payload.sub,
      email: payload.email,
      displayName: typeof payload.displayName === "string" ? payload.displayName : undefined,
      username: typeof payload.username === "string" ? payload.username : undefined,
    };
  } catch {
    return null;
  }
}

export async function getAcademyAuthFromRequest(req: NextRequest) {
  const legacy = await verifyAcademyAuthToken(req.cookies.get(ACADEMY_AUTH_COOKIE)?.value);
  if (legacy) return legacy;
  // Phase 23: legacy cookie retired — fall back to unified cookie for new sessions
  const unified = await verifyUnifiedSession(req.cookies.get(UNIFIED_SESSION_COOKIE)?.value);
  if (unified?.accountId) {
    return {
      accountId: unified.accountId,
      email: unified.email ?? "",
      displayName: unified.displayName ?? undefined,
      username: unified.username ?? undefined,
    };
  }
  return null;
}

function shouldUseSecureCookie() {
  // Local production builds are often tested on http://localhost.
  // A Secure cookie is ignored by the browser on http, which makes academy login look successful
  // but the next page cannot see the session. Set TECPEY_COOKIE_SECURE=true on HTTPS production.
  if (process.env.TECPEY_COOKIE_SECURE === "true") return true;
  if (process.env.TECPEY_COOKIE_SECURE === "false") return false;
  const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "";
  if (siteUrl.startsWith("https://")) return true;
  if (siteUrl.startsWith("http://localhost") || siteUrl.startsWith("http://127.0.0.1")) return false;
  return false;
}

export function setAcademyAuthCookie(response: NextResponse, token: string) {
  response.cookies.set(ACADEMY_AUTH_COOKIE, token, {
    path: "/",
    httpOnly: true,
    secure: shouldUseSecureCookie(),
    sameSite: "lax",
    maxAge: Number(process.env.TECPEY_ACADEMY_AUTH_MAX_AGE_SECONDS || 60 * 60 * 24 * 30),
  });
}

export function clearAcademyAuthCookie(response: NextResponse) {
  response.cookies.delete(ACADEMY_AUTH_COOKIE);
}
